#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <unistd.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>
#include "types.h"
#include "const.h"
#include "util.h"

int partition(int arr[], int lo, int hi);

int serial_binsearch(int x, int val[], int n) {
    int low = 0, high = n-1, mid;

    while (low < high){
        mid = (low+high)/2;

        if (x < val[mid])
            high = mid - 1;
        else if (x > val[mid])
            low = mid + 1;
        else
            return mid;
    }
    return -1;
}

// TODO: implement
int parallel_binsearch() {

    return 0;
}


int main(int argc, char** argv) {

    /* TODO: move this time measurement to right before the execution of each binsearch algorithms
     * in your experiment code. It now stands here just for demonstrating time measurement. */
    clock_t cbegin = clock();

    printf("[binsearch] Starting up...\n");

    /* Get the number of CPU cores available */
    printf("[binsearch] Number of cores available: '%ld'\n",
           sysconf(_SC_NPROCESSORS_ONLN));

    /* TODO: parse arguments with getopt */
    char *Pflg, *Eflg, *Tflg;
    int T;
    int c;
    while ((c = getopt (argc, argv, "T:E:P:")) != -1)
      switch (c){
        case 'E':
          Eflg = optarg;
          break;
        case 'P':
          Pflg = optarg;
          break;
        case 'T':
          Tflg = optarg;
          break;
      }
    printf("E flag: %s T flag: %s and P flag: %s\n", Eflg, Tflg, Pflg);
    T = atoi(Tflg);
    /* TODO: start datagen here as a child process. */
    struct sockaddr_un addr;
    int fd, rc;
    char buf[1000];

    if ( (fd = socket(AF_UNIX, SOCK_STREAM, 0)) == -1) {
    perror("socket error");
    exit(-1);
    }

    if(connect(fd, (struct sockaddr*)&addr, sizeof(addr))== -1){
      perror("connect error");
      exit(-1);
    }

    if (write(fd, buf, rc) != rc) {
      if (rc > 0) fprintf(stderr,"partial write");
      else {
        perror("write error");
        exit(-1);
      }
    }

    /* TODO: implement code for your experiments using data provided by datagen and your
     * serial and parallel versions of binsearch.
     * */

    /* TODO: connect to datagen and ask for the necessary data in each experiment round.
     * Create a Unix domain socket with DSOCKET_PATH (see const.h).
     * Talk to datagen using the messages specified in the assignment description document.
     * Read the values generated by datagen from the socket and use them to run your
     * experiments
     * */
    //read();

    /* Probe time elapsed. */
    clock_t cend = clock();

    // Time elapsed in miliseconds.
    double time_elapsed = ((double) (cend - cbegin) / CLOCKS_PER_SEC) * 1000;

    printf("Time elapsed '%lf' [ms].\n", time_elapsed);

    exit(0);
}
